package grupog.agendamlg.beans;

import grupog.agendamlg.entities.Localidad;
import grupog.agendamlg.entities.Provincia;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author Jean Paul Beaudry
 */
@ManagedBean
@SessionScoped
public class ProvinciaBean implements Serializable {

    /**
     * Creates a new instance of ProvinciaBean
     */
    private List<Provincia> provincias;
    private List<Localidad> localidades;
    private String provincia;
    private String localidad;

    public ProvinciaBean() {
    }

    @PostConstruct
    public void init() {
        provincia = "Málaga";
        localidad = "Málaga";
        provincias = new ArrayList<>();
        Provincia provincia2 = new Provincia();
        Provincia provincia3 = new Provincia();
        Provincia provincia4 = new Provincia();
        Provincia provincia5 = new Provincia();
        Provincia provincia6 = new Provincia();
        Provincia provincia7 = new Provincia();
        Provincia provincia8 = new Provincia();
        Provincia provincia9 = new Provincia();
        provincia2.setNombre("Granada");
        provincia3.setNombre("Málaga");
        provincia4.setNombre("Sevilla");
        provincia5.setNombre("Huelva");
        provincia6.setNombre("Almería");
        provincia7.setNombre("Cádiz");
        provincia8.setNombre("Jaén");
        provincia9.setNombre("Córdoba");

        //Granada
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Agrón", provincia2));
        localidades.add(new Localidad("Alamedilla", provincia2));
        localidades.add(new Localidad("Albolote", provincia2));
        localidades.add(new Localidad("Albondón", provincia2));
        localidades.add(new Localidad("Albuñán", provincia2));
        localidades.add(new Localidad("Albuñol", provincia2));
        localidades.add(new Localidad("Albuñuelas", provincia2));
        localidades.add(new Localidad("Aldeire", provincia2));
        localidades.add(new Localidad("Alfacar", provincia2));
        localidades.add(new Localidad("Algarinejo", provincia2));
        localidades.add(new Localidad("Alhama de Granada", provincia2));
        localidades.add(new Localidad("Alhendín", provincia2));
        localidades.add(new Localidad("Alicún de Ortega", provincia2));
        localidades.add(new Localidad("Almegíjar", provincia2));
        localidades.add(new Localidad("Almuñécar", provincia2));
        localidades.add(new Localidad("Alpujarra de la Sierra", provincia2));
        localidades.add(new Localidad("Alquife", provincia2));
        localidades.add(new Localidad("Arenas del Rey", provincia2));
        localidades.add(new Localidad("Armilla", provincia2));
        localidades.add(new Localidad("Atarfe", provincia2));
        localidades.add(new Localidad("Baza", provincia2));
        localidades.add(new Localidad("Beas de Granada", provincia2));
        localidades.add(new Localidad("Beas de Guadix", provincia2));
        localidades.add(new Localidad("Benalúa", provincia2));
        localidades.add(new Localidad("Benalúa de las Villas", provincia2));
        localidades.add(new Localidad("Benamaurel", provincia2));
        localidades.add(new Localidad("Bérchules", provincia2));
        localidades.add(new Localidad("Bubión", provincia2));
        localidades.add(new Localidad("Busquístar", provincia2));
        localidades.add(new Localidad("Cacín", provincia2));
        localidades.add(new Localidad("Cádiar", provincia2));
        localidades.add(new Localidad("Cájar", provincia2));
        localidades.add(new Localidad("Calahorra, La", provincia2));
        localidades.add(new Localidad("Calicasas", provincia2));
        localidades.add(new Localidad("Campotéjar", provincia2));
        localidades.add(new Localidad("Caniles", provincia2));
        localidades.add(new Localidad("Cáñar", provincia2));
        localidades.add(new Localidad("Capileira", provincia2));
        localidades.add(new Localidad("Carataunas", provincia2));
        localidades.add(new Localidad("Cástaras", provincia2));
        localidades.add(new Localidad("Castilléjar", provincia2));
        localidades.add(new Localidad("Castril", provincia2));
        localidades.add(new Localidad("Cenes de la Vega", provincia2));
        localidades.add(new Localidad("Chauchina", provincia2));
        localidades.add(new Localidad("Chimeneas", provincia2));
        localidades.add(new Localidad("Churriana de la Vega", provincia2));
        localidades.add(new Localidad("Cijuela", provincia2));
        localidades.add(new Localidad("Cogollos de Guadix", provincia2));
        localidades.add(new Localidad("Cogollos de la Vega", provincia2));
        localidades.add(new Localidad("Colomera", provincia2));
        localidades.add(new Localidad("Cortes de Baza", provincia2));
        localidades.add(new Localidad("Cortes y Graena", provincia2));
        localidades.add(new Localidad("Cuevas del Campo", provincia2));
        localidades.add(new Localidad("Cúllar", provincia2));
        localidades.add(new Localidad("Cúllar Vega", provincia2));
        localidades.add(new Localidad("Darro", provincia2));
        localidades.add(new Localidad("Dehesas de Guadix", provincia2));
        localidades.add(new Localidad("Dehesas Viejas", provincia2));
        localidades.add(new Localidad("Deifontes", provincia2));
        localidades.add(new Localidad("Diezma", provincia2));
        localidades.add(new Localidad("Dílar", provincia2));
        localidades.add(new Localidad("Dólar", provincia2));
        localidades.add(new Localidad("Dúdar", provincia2));
        localidades.add(new Localidad("Dúrcal", provincia2));
        localidades.add(new Localidad("Escúzar", provincia2));
        localidades.add(new Localidad("Ferreira", provincia2));
        localidades.add(new Localidad("Fonelas", provincia2));
        localidades.add(new Localidad("Freila", provincia2));
        localidades.add(new Localidad("Fuente Vaqueros", provincia2));
        localidades.add(new Localidad("Gabias, Las", provincia2));
        localidades.add(new Localidad("Galera", provincia2));
        localidades.add(new Localidad("Gobernador", provincia2));
        localidades.add(new Localidad("Gójar", provincia2));
        localidades.add(new Localidad("Gor", provincia2));
        localidades.add(new Localidad("Gorafe", provincia2));
        localidades.add(new Localidad("Granada", provincia2));
        localidades.add(new Localidad("Guadahortuna", provincia2));
        localidades.add(new Localidad("Guadix", provincia2));
        localidades.add(new Localidad("Guajares, Los", provincia2));
        localidades.add(new Localidad("Gualchos", provincia2));
        localidades.add(new Localidad("Güejar Sierra", provincia2));
        localidades.add(new Localidad("Güevéjar", provincia2));
        localidades.add(new Localidad("Huélago", provincia2));
        localidades.add(new Localidad("Huéneja", provincia2));
        localidades.add(new Localidad("Huéscar", provincia2));
        localidades.add(new Localidad("Huétor de Santillán", provincia2));
        localidades.add(new Localidad("Huétor Tájar", provincia2));
        localidades.add(new Localidad("Huétor Vega", provincia2));
        localidades.add(new Localidad("Illora", provincia2));
        localidades.add(new Localidad("Itrabo", provincia2));
        localidades.add(new Localidad("Iznalloz", provincia2));
        localidades.add(new Localidad("Jayena", provincia2));
        localidades.add(new Localidad("Jerez del Marquesado", provincia2));
        localidades.add(new Localidad("Jete", provincia2));
        localidades.add(new Localidad("Jun", provincia2));
        localidades.add(new Localidad("Juviles", provincia2));
        localidades.add(new Localidad("Láchar", provincia2));
        localidades.add(new Localidad("Lanjarón", provincia2));
        localidades.add(new Localidad("Lanteira", provincia2));
        localidades.add(new Localidad("Lecrín", provincia2));
        localidades.add(new Localidad("Lentegí", provincia2));
        localidades.add(new Localidad("Lobras", provincia2));
        localidades.add(new Localidad("Loja", provincia2));
        localidades.add(new Localidad("Lugros", provincia2));
        localidades.add(new Localidad("Lújar", provincia2));
        localidades.add(new Localidad("Malahá, La", provincia2));
        localidades.add(new Localidad("Maracena", provincia2));
        localidades.add(new Localidad("Marchal", provincia2));
        localidades.add(new Localidad("Moclín", provincia2));
        localidades.add(new Localidad("Molvízar", provincia2));
        localidades.add(new Localidad("Monachil", provincia2));
        localidades.add(new Localidad("Montefrío", provincia2));
        localidades.add(new Localidad("Montejícar", provincia2));
        localidades.add(new Localidad("Montillana", provincia2));
        localidades.add(new Localidad("Moraleda de Zafayona", provincia2));
        localidades.add(new Localidad("Morelábor", provincia2));
        localidades.add(new Localidad("Motril", provincia2));
        localidades.add(new Localidad("Murtas", provincia2));
        localidades.add(new Localidad("Nevada", provincia2));
        localidades.add(new Localidad("Nigüelas", provincia2));
        localidades.add(new Localidad("Nívar", provincia2));
        localidades.add(new Localidad("Ogíjares", provincia2));
        localidades.add(new Localidad("Orce", provincia2));
        localidades.add(new Localidad("Órgiva", provincia2));
        localidades.add(new Localidad("Otívar", provincia2));
        localidades.add(new Localidad("Padul", provincia2));
        localidades.add(new Localidad("Pampaneira", provincia2));
        localidades.add(new Localidad("Pedro Martínez", provincia2));
        localidades.add(new Localidad("Peligros", provincia2));
        localidades.add(new Localidad("Peza, La", provincia2));
        localidades.add(new Localidad("Pinar, El", provincia2));
        localidades.add(new Localidad("Pinos Genil", provincia2));
        localidades.add(new Localidad("Pinos Puente", provincia2));
        localidades.add(new Localidad("Píñar", provincia2));
        localidades.add(new Localidad("Polícar", provincia2));
        localidades.add(new Localidad("Polopos", provincia2));
        localidades.add(new Localidad("Pórtugos", provincia2));
        localidades.add(new Localidad("Puebla de Don Fadrique", provincia2));
        localidades.add(new Localidad("Pulianas", provincia2));
        localidades.add(new Localidad("Purullena", provincia2));
        localidades.add(new Localidad("Quéntar", provincia2));
        localidades.add(new Localidad("Rubite", provincia2));
        localidades.add(new Localidad("Salar", provincia2));
        localidades.add(new Localidad("Salobreña", provincia2));
        localidades.add(new Localidad("Santa Cruz del Comercio", provincia2));
        localidades.add(new Localidad("Santa Fe", provincia2));
        localidades.add(new Localidad("Soportújar", provincia2));
        localidades.add(new Localidad("Sorvilán", provincia2));
        localidades.add(new Localidad("Taha, La", provincia2));
        localidades.add(new Localidad("Torre-Cardela", provincia2));
        localidades.add(new Localidad("Torvizcón", provincia2));
        localidades.add(new Localidad("Trevélez", provincia2));
        localidades.add(new Localidad("Turón", provincia2));
        localidades.add(new Localidad("Ugíjar", provincia2));
        localidades.add(new Localidad("Valderrubio", provincia2));
        localidades.add(new Localidad("Valle, El", provincia2));
        localidades.add(new Localidad("Valle del Zalabí", provincia2));
        localidades.add(new Localidad("Válor", provincia2));
        localidades.add(new Localidad("Vegas del Genil", provincia2));
        localidades.add(new Localidad("Vélez de Benaudalla", provincia2));
        localidades.add(new Localidad("Ventas de Huelma", provincia2));
        localidades.add(new Localidad("Villa de Otura", provincia2));
        localidades.add(new Localidad("Villamena", provincia2));
        localidades.add(new Localidad("Villanueva de las Torres", provincia2));
        localidades.add(new Localidad("Villanueva Mesía", provincia2));
        localidades.add(new Localidad("Víznar", provincia2));
        localidades.add(new Localidad("Zafarraya", provincia2));
        localidades.add(new Localidad("Zagra", provincia2));
        localidades.add(new Localidad("Zubia, La", provincia2));
        localidades.add(new Localidad("Zújar", provincia2));
        provincia2.setLocalidades(localidades);
        provincias.add(provincia2);

        //Sevilla
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Aguadulce", provincia4));
        localidades.add(new Localidad("Alanís", provincia4));
        localidades.add(new Localidad("Albaida del Aljarafe", provincia4));
        localidades.add(new Localidad("Alcalá de Guadaíra", provincia4));
        localidades.add(new Localidad("Alcalá del Río", provincia4));
        localidades.add(new Localidad("Alcolea del Río", provincia4));
        localidades.add(new Localidad("Algaba, La", provincia4));
        localidades.add(new Localidad("Algámitas", provincia4));
        localidades.add(new Localidad("Almadén de la Plata", provincia4));
        localidades.add(new Localidad("Almensilla", provincia4));
        localidades.add(new Localidad("Arahal", provincia4));
        localidades.add(new Localidad("Aznalcázar", provincia4));
        localidades.add(new Localidad("Aznalcóllar", provincia4));
        localidades.add(new Localidad("Badolatosa", provincia4));
        localidades.add(new Localidad("Benacazón", provincia4));
        localidades.add(new Localidad("Bollullos de la Mitación", provincia4));
        localidades.add(new Localidad("Bormujos", provincia4));
        localidades.add(new Localidad("Brenes", provincia4));
        localidades.add(new Localidad("Burguillos", provincia4));
        localidades.add(new Localidad("Cabezas de San Juan, Las", provincia4));
        localidades.add(new Localidad("Camas", provincia4));
        localidades.add(new Localidad("Campana, La", provincia4));
        localidades.add(new Localidad("Cantillana", provincia4));
        localidades.add(new Localidad("Cañada Rosal", provincia4));
        localidades.add(new Localidad("Carmona", provincia4));
        localidades.add(new Localidad("Carrión de los Céspedes", provincia4));
        localidades.add(new Localidad("Casariche", provincia4));
        localidades.add(new Localidad("Castilblanco de los Arroyos", provincia4));
        localidades.add(new Localidad("Castilleja de Guzmán", provincia4));
        localidades.add(new Localidad("Castilleja de la Cuesta", provincia4));
        localidades.add(new Localidad("Castilleja del Campo", provincia4));
        localidades.add(new Localidad("Castillo de las Guardas, El", provincia4));
        localidades.add(new Localidad("Cazalla de la Sierra", provincia4));
        localidades.add(new Localidad("Constantina", provincia4));
        localidades.add(new Localidad("Coria del Río", provincia4));
        localidades.add(new Localidad("Coripe", provincia4));
        localidades.add(new Localidad("Coronil, El", provincia4));
        localidades.add(new Localidad("Corrales, Los", provincia4));
        localidades.add(new Localidad("Cuervo de Sevilla, El", provincia4));
        localidades.add(new Localidad("Dos Hermanas", provincia4));
        localidades.add(new Localidad("Écija", provincia4));
        localidades.add(new Localidad("Espartinas", provincia4));
        localidades.add(new Localidad("Estepa", provincia4));
        localidades.add(new Localidad("Fuentes de Andalucía", provincia4));
        localidades.add(new Localidad("Garrobo, El", provincia4));
        localidades.add(new Localidad("Gelves", provincia4));
        localidades.add(new Localidad("Gerena", provincia4));
        localidades.add(new Localidad("Gilena", provincia4));
        localidades.add(new Localidad("Gines", provincia4));
        localidades.add(new Localidad("Guadalcanal", provincia4));
        localidades.add(new Localidad("Guillena", provincia4));
        localidades.add(new Localidad("Herrera", provincia4));
        localidades.add(new Localidad("Huévar del Aljarafe", provincia4));
        localidades.add(new Localidad("Isla Mayor", provincia4));
        localidades.add(new Localidad("Lantejuela", provincia4));
        localidades.add(new Localidad("Lebrija", provincia4));
        localidades.add(new Localidad("Lora de Estepa", provincia4));
        localidades.add(new Localidad("Lora del Río", provincia4));
        localidades.add(new Localidad("Luisiana, La", provincia4));
        localidades.add(new Localidad("Madroño, El", provincia4));
        localidades.add(new Localidad("Mairena del Alcor", provincia4));
        localidades.add(new Localidad("Mairena del Aljarafe", provincia4));
        localidades.add(new Localidad("Marchena", provincia4));
        localidades.add(new Localidad("Marinaleda", provincia4));
        localidades.add(new Localidad("Martín de la Jara", provincia4));
        localidades.add(new Localidad("Molares, Los", provincia4));
        localidades.add(new Localidad("Montellano", provincia4));
        localidades.add(new Localidad("Morón de la Frontera", provincia4));
        localidades.add(new Localidad("Navas de la Concepción, Las", provincia4));
        localidades.add(new Localidad("Olivares", provincia4));
        localidades.add(new Localidad("Osuna", provincia4));
        localidades.add(new Localidad("Palacios y Villafranca, Los", provincia4));
        localidades.add(new Localidad("Palomares del Río", provincia4));
        localidades.add(new Localidad("Paradas", provincia4));
        localidades.add(new Localidad("Pedrera", provincia4));
        localidades.add(new Localidad("Pedroso, El", provincia4));
        localidades.add(new Localidad("Peñaflor", provincia4));
        localidades.add(new Localidad("Pilas", provincia4));
        localidades.add(new Localidad("Pruna", provincia4));
        localidades.add(new Localidad("Puebla de Cazalla, La", provincia4));
        localidades.add(new Localidad("Puebla de los Infantes, La", provincia4));
        localidades.add(new Localidad("Puebla del Río, La", provincia4));
        localidades.add(new Localidad("Real de la Jara, El", provincia4));
        localidades.add(new Localidad("Rinconada, La", provincia4));
        localidades.add(new Localidad("Roda de Andalucía, La", provincia4));
        localidades.add(new Localidad("Ronquillo, El", provincia4));
        localidades.add(new Localidad("Rubio, El", provincia4));
        localidades.add(new Localidad("Salteras", provincia4));
        localidades.add(new Localidad("San Juan de Aznalfarache", provincia4));
        localidades.add(new Localidad("Sanlúcar la Mayor", provincia4));
        localidades.add(new Localidad("San Nicolás del Puerto", provincia4));
        localidades.add(new Localidad("Santiponce", provincia4));
        localidades.add(new Localidad("Saucejo, El", provincia4));
        localidades.add(new Localidad("Sevilla", provincia4));
        localidades.add(new Localidad("Tocina", provincia4));
        localidades.add(new Localidad("Tomares", provincia4));
        localidades.add(new Localidad("Umbrete", provincia4));
        localidades.add(new Localidad("Utrera", provincia4));
        localidades.add(new Localidad("Valencina de la Concepción", provincia4));
        localidades.add(new Localidad("Villamanrique de la Condesa", provincia4));
        localidades.add(new Localidad("Villanueva del Ariscal", provincia4));
        localidades.add(new Localidad("Villanueva del Río y Minas", provincia4));
        localidades.add(new Localidad("Villanueva de San Juan", provincia4));
        localidades.add(new Localidad("Villaverde del Río", provincia4));
        localidades.add(new Localidad("Viso del Alcor, El", provincia4));
        provincia4.setLocalidades(localidades);
        provincias.add(provincia4);

        //Huelva
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Alájar", provincia5));
        localidades.add(new Localidad("Aljaraque", provincia5));
        localidades.add(new Localidad("Almendro, El", provincia5));
        localidades.add(new Localidad("Almonaster la Real", provincia5));
        localidades.add(new Localidad("Almonte", provincia5));
        localidades.add(new Localidad("Alosno", provincia5));
        localidades.add(new Localidad("Aracena", provincia5));
        localidades.add(new Localidad("Aroche", provincia5));
        localidades.add(new Localidad("Arroyomolinos de León", provincia5));
        localidades.add(new Localidad("Ayamonte", provincia5));
        localidades.add(new Localidad("Beas", provincia5));
        localidades.add(new Localidad("Berrocal", provincia5));
        localidades.add(new Localidad("Bollullos Par del Condado", provincia5));
        localidades.add(new Localidad("Bonares", provincia5));
        localidades.add(new Localidad("Cabezas Rubias", provincia5));
        localidades.add(new Localidad("Cala", provincia5));
        localidades.add(new Localidad("Calañas", provincia5));
        localidades.add(new Localidad("Campillo, El", provincia5));
        localidades.add(new Localidad("Campofrío", provincia5));
        localidades.add(new Localidad("Cañaveral de León", provincia5));
        localidades.add(new Localidad("Cartaya", provincia5));
        localidades.add(new Localidad("Castaño del Robledo", provincia5));
        localidades.add(new Localidad("Cerro de Andévalo, El", provincia5));
        localidades.add(new Localidad("Chucena", provincia5));
        localidades.add(new Localidad("Corteconcepción", provincia5));
        localidades.add(new Localidad("Cortegana", provincia5));
        localidades.add(new Localidad("Cortelazor", provincia5));
        localidades.add(new Localidad("Cumbres de Enmedio", provincia5));
        localidades.add(new Localidad("Cumbres de San Bartolomé", provincia5));
        localidades.add(new Localidad("Cumbres Mayores", provincia5));
        localidades.add(new Localidad("Encinasola", provincia5));
        localidades.add(new Localidad("Escacena del Campo", provincia5));
        localidades.add(new Localidad("Fuenteheridos", provincia5));
        localidades.add(new Localidad("Galaroza", provincia5));
        localidades.add(new Localidad("Gibraleón", provincia5));
        localidades.add(new Localidad("Granada de Río-Tinto, La", provincia5));
        localidades.add(new Localidad("Granado, El", provincia5));
        localidades.add(new Localidad("Higuera de la Sierra", provincia5));
        localidades.add(new Localidad("Hinojales", provincia5));
        localidades.add(new Localidad("Hinojos", provincia5));
        localidades.add(new Localidad("Huelva", provincia5));
        localidades.add(new Localidad("Isla Cristina", provincia5));
        localidades.add(new Localidad("Jabugo", provincia5));
        localidades.add(new Localidad("Lepe", provincia5));
        localidades.add(new Localidad("Linares de la Sierra", provincia5));
        localidades.add(new Localidad("Lucena del Puerto", provincia5));
        localidades.add(new Localidad("Manzanilla", provincia5));
        localidades.add(new Localidad("Marines, Los", provincia5));
        localidades.add(new Localidad("Minas de Riotinto", provincia5));
        localidades.add(new Localidad("Moguer", provincia5));
        localidades.add(new Localidad("Nava, La", provincia5));
        localidades.add(new Localidad("Nerva", provincia5));
        localidades.add(new Localidad("Niebla", provincia5));
        localidades.add(new Localidad("Palma del Condado, La", provincia5));
        localidades.add(new Localidad("Palos de la Frontera", provincia5));
        localidades.add(new Localidad("Paterna del Campo", provincia5));
        localidades.add(new Localidad("Paymogo", provincia5));
        localidades.add(new Localidad("Puebla de Guzmán", provincia5));
        localidades.add(new Localidad("Puerto Moral", provincia5));
        localidades.add(new Localidad("Punta Umbría", provincia5));
        localidades.add(new Localidad("Rociana del Condado", provincia5));
        localidades.add(new Localidad("Rosal de la Frontera", provincia5));
        localidades.add(new Localidad("San Bartolomé de la Torre", provincia5));
        localidades.add(new Localidad("San Juan del Puerto", provincia5));
        localidades.add(new Localidad("Sanlúcar de Guadiana", provincia5));
        localidades.add(new Localidad("San Silvestre de Guzmán", provincia5));
        localidades.add(new Localidad("Santa Ana la Real", provincia5));
        localidades.add(new Localidad("Santa Bárbara de Casa", provincia5));
        localidades.add(new Localidad("Santa Olalla del Cala", provincia5));
        localidades.add(new Localidad("Trigueros", provincia5));
        localidades.add(new Localidad("Valdelarco", provincia5));
        localidades.add(new Localidad("Valverde del Camino", provincia5));
        localidades.add(new Localidad("Villablanca", provincia5));
        localidades.add(new Localidad("Villalba del Alcor", provincia5));
        localidades.add(new Localidad("Villanueva de las Cruces", provincia5));
        localidades.add(new Localidad("Villanueva de los Castillejos", provincia5));
        localidades.add(new Localidad("Villarrasa", provincia5));
        localidades.add(new Localidad("Zalamea la Real", provincia5));
        localidades.add(new Localidad("Zufre", provincia5));
        provincia5.setLocalidades(localidades);
        provincias.add(provincia5);

        //Almeria
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Abla", provincia6));
        localidades.add(new Localidad("Abrucena", provincia6));
        localidades.add(new Localidad("Adra", provincia6));
        localidades.add(new Localidad("Albánchez", provincia6));
        localidades.add(new Localidad("Alboloduy", provincia6));
        localidades.add(new Localidad("Albox", provincia6));
        localidades.add(new Localidad("Alcolea", provincia6));
        localidades.add(new Localidad("Alcóntar", provincia6));
        localidades.add(new Localidad("Alcudia de Monteagud", provincia6));
        localidades.add(new Localidad("Alhabia", provincia6));
        localidades.add(new Localidad("Alhama de Almería", provincia6));
        localidades.add(new Localidad("Alicún", provincia6));
        localidades.add(new Localidad("Almería", provincia6));
        localidades.add(new Localidad("Almócita", provincia6));
        localidades.add(new Localidad("Alsodux", provincia6));
        localidades.add(new Localidad("Antas", provincia6));
        localidades.add(new Localidad("Arboleas", provincia6));
        localidades.add(new Localidad("Armuña de Almanzora", provincia6));
        localidades.add(new Localidad("Bacares", provincia6));
        localidades.add(new Localidad("Bayárcal", provincia6));
        localidades.add(new Localidad("Bayarque", provincia6));
        localidades.add(new Localidad("Bédar", provincia6));
        localidades.add(new Localidad("Beires", provincia6));
        localidades.add(new Localidad("Benahadux", provincia6));
        localidades.add(new Localidad("Benitagla", provincia6));
        localidades.add(new Localidad("Benizalón", provincia6));
        localidades.add(new Localidad("Bentarique", provincia6));
        localidades.add(new Localidad("Berja", provincia6));
        localidades.add(new Localidad("Canjáyar", provincia6));
        localidades.add(new Localidad("Cantoria", provincia6));
        localidades.add(new Localidad("Carboneras", provincia6));
        localidades.add(new Localidad("Castro de Filabres", provincia6));
        localidades.add(new Localidad("Chercos", provincia6));
        localidades.add(new Localidad("Chirivel", provincia6));
        localidades.add(new Localidad("Cóbdar", provincia6));
        localidades.add(new Localidad("Cuevas del Almanzora", provincia6));
        localidades.add(new Localidad("Dalías", provincia6));
        localidades.add(new Localidad("Ejido, El", provincia6));
        localidades.add(new Localidad("Enix", provincia6));
        localidades.add(new Localidad("Felix", provincia6));
        localidades.add(new Localidad("Fines", provincia6));
        localidades.add(new Localidad("Fiñana", provincia6));
        localidades.add(new Localidad("Fondón", provincia6));
        localidades.add(new Localidad("Gádor", provincia6));
        localidades.add(new Localidad("Gallardos, Los", provincia6));
        localidades.add(new Localidad("Garrucha", provincia6));
        localidades.add(new Localidad("Gérgal", provincia6));
        localidades.add(new Localidad("Huécija", provincia6));
        localidades.add(new Localidad("Huércal de Almería", provincia6));
        localidades.add(new Localidad("Huércal-Overa", provincia6));
        localidades.add(new Localidad("Illar", provincia6));
        localidades.add(new Localidad("Instinción", provincia6));
        localidades.add(new Localidad("Laroya", provincia6));
        localidades.add(new Localidad("Láujar de Andarax", provincia6));
        localidades.add(new Localidad("Líjar", provincia6));
        localidades.add(new Localidad("Lubrín", provincia6));
        localidades.add(new Localidad("Lucainena de las Torres", provincia6));
        localidades.add(new Localidad("Lúcar", provincia6));
        localidades.add(new Localidad("Macael", provincia6));
        localidades.add(new Localidad("María", provincia6));
        localidades.add(new Localidad("Mojácar", provincia6));
        localidades.add(new Localidad("Mojonera, La", provincia6));
        localidades.add(new Localidad("Nacimiento", provincia6));
        localidades.add(new Localidad("Níjar", provincia6));
        localidades.add(new Localidad("Ohanes", provincia6));
        localidades.add(new Localidad("Olula de Castro", provincia6));
        localidades.add(new Localidad("Olula del Río", provincia6));
        localidades.add(new Localidad("Oria", provincia6));
        localidades.add(new Localidad("Padules", provincia6));
        localidades.add(new Localidad("Partaloa", provincia6));
        localidades.add(new Localidad("Paterna del Río", provincia6));
        localidades.add(new Localidad("Pechina", provincia6));
        localidades.add(new Localidad("Pulpí", provincia6));
        localidades.add(new Localidad("Purchena", provincia6));
        localidades.add(new Localidad("Rágol", provincia6));
        localidades.add(new Localidad("Rioja", provincia6));
        localidades.add(new Localidad("Roquetas de Mar", provincia6));
        localidades.add(new Localidad("Santa Cruz de Marchena", provincia6));
        localidades.add(new Localidad("Santa Fe de Mondújar", provincia6));
        localidades.add(new Localidad("Senés", provincia6));
        localidades.add(new Localidad("Serón", provincia6));
        localidades.add(new Localidad("Sierro", provincia6));
        localidades.add(new Localidad("Somontín", provincia6));
        localidades.add(new Localidad("Sorbas", provincia6));
        localidades.add(new Localidad("Suflí", provincia6));
        localidades.add(new Localidad("Tabernas", provincia6));
        localidades.add(new Localidad("Taberno", provincia6));
        localidades.add(new Localidad("Tahal", provincia6));
        localidades.add(new Localidad("Terque", provincia6));
        localidades.add(new Localidad("Tíjola", provincia6));
        localidades.add(new Localidad("Tres Villas, Las", provincia6));
        localidades.add(new Localidad("Turre", provincia6));
        localidades.add(new Localidad("Turrillas", provincia6));
        localidades.add(new Localidad("Uleila del Campo", provincia6));
        localidades.add(new Localidad("Urrácal", provincia6));
        localidades.add(new Localidad("Velefique", provincia6));
        localidades.add(new Localidad("Vélez-Blanco", provincia6));
        localidades.add(new Localidad("Vélez-Rubio", provincia6));
        localidades.add(new Localidad("Vera", provincia6));
        localidades.add(new Localidad("Viator", provincia6));
        localidades.add(new Localidad("Vícar", provincia6));
        localidades.add(new Localidad("Zurgena", provincia6));
        provincia6.setLocalidades(localidades);
        provincias.add(provincia6);

        //Cadiz
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Alcalá de los Gazules", provincia7));
        localidades.add(new Localidad("Alcalá del Valle", provincia7));
        localidades.add(new Localidad("Algar", provincia7));
        localidades.add(new Localidad("Algeciras", provincia7));
        localidades.add(new Localidad("Algodonales", provincia7));
        localidades.add(new Localidad("Arcos de la Frontera", provincia7));
        localidades.add(new Localidad("Barbate", provincia7));
        localidades.add(new Localidad("Barrios, Los", provincia7));
        localidades.add(new Localidad("Benalup-Casas Viejas", provincia7));
        localidades.add(new Localidad("Benaocaz", provincia7));
        localidades.add(new Localidad("Bornos", provincia7));
        localidades.add(new Localidad("Bosque, El", provincia7));
        localidades.add(new Localidad("Cádiz", provincia7));
        localidades.add(new Localidad("Castellar de la Frontera", provincia7));
        localidades.add(new Localidad("Chiclana de la Frontera", provincia7));
        localidades.add(new Localidad("Chipiona", provincia7));
        localidades.add(new Localidad("Conil de la Frontera", provincia7));
        localidades.add(new Localidad("Espera", provincia7));
        localidades.add(new Localidad("Gastor, El", provincia7));
        localidades.add(new Localidad("Grazalema", provincia7));
        localidades.add(new Localidad("Jerez de la Frontera", provincia7));
        localidades.add(new Localidad("Jimena de la Frontera", provincia7));
        localidades.add(new Localidad("Línea de la Concepción, La", provincia7));
        localidades.add(new Localidad("Medina-Sidonia", provincia7));
        localidades.add(new Localidad("Olvera", provincia7));
        localidades.add(new Localidad("Paterna de Rivera", provincia7));
        localidades.add(new Localidad("Prado del Rey", provincia7));
        localidades.add(new Localidad("Puerto de Santa María, El", provincia7));
        localidades.add(new Localidad("Puerto Real", provincia7));
        localidades.add(new Localidad("Puerto Serrano", provincia7));
        localidades.add(new Localidad("Rota", provincia7));
        localidades.add(new Localidad("San Fernando", provincia7));
        localidades.add(new Localidad("San José del Valle", provincia7));
        localidades.add(new Localidad("Sanlúcar de Barrameda", provincia7));
        localidades.add(new Localidad("San Roque", provincia7));
        localidades.add(new Localidad("Setenil de las Bodegas", provincia7));
        localidades.add(new Localidad("Tarifa", provincia7));
        localidades.add(new Localidad("Torre Alháquime", provincia7));
        localidades.add(new Localidad("Trebujena", provincia7));
        localidades.add(new Localidad("Ubrique", provincia7));
        localidades.add(new Localidad("Vejer de la Frontera", provincia7));
        localidades.add(new Localidad("Villaluenga del Rosario", provincia7));
        localidades.add(new Localidad("Villamartín", provincia7));
        localidades.add(new Localidad("Zahara", provincia7));
        provincia7.setLocalidades(localidades);
        provincias.add(provincia7);

        //Jaen
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Albanchez de Mágina", provincia8));
        localidades.add(new Localidad("Alcalá la Real", provincia8));
        localidades.add(new Localidad("Alcaudete", provincia8));
        localidades.add(new Localidad("Aldeaquemada", provincia8));
        localidades.add(new Localidad("Andújar", provincia8));
        localidades.add(new Localidad("Arjona", provincia8));
        localidades.add(new Localidad("Arjonilla", provincia8));
        localidades.add(new Localidad("Arquillos", provincia8));
        localidades.add(new Localidad("Arroyo del Ojanco", provincia8));
        localidades.add(new Localidad("Baeza", provincia8));
        localidades.add(new Localidad("Bailén", provincia8));
        localidades.add(new Localidad("Baños de la Encina", provincia8));
        localidades.add(new Localidad("Beas de Segura", provincia8));
        localidades.add(new Localidad("Bedmar y Garcíez", provincia8));
        localidades.add(new Localidad("Begíjar", provincia8));
        localidades.add(new Localidad("Bélmez de la Moraleda", provincia8));
        localidades.add(new Localidad("Benatae", provincia8));
        localidades.add(new Localidad("Cabra del Santo Cristo", provincia8));
        localidades.add(new Localidad("Cambil", provincia8));
        localidades.add(new Localidad("Campillo de Arenas", provincia8));
        localidades.add(new Localidad("Canena", provincia8));
        localidades.add(new Localidad("Carboneros", provincia8));
        localidades.add(new Localidad("Cárcheles", provincia8));
        localidades.add(new Localidad("Carolina, La", provincia8));
        localidades.add(new Localidad("Castellar", provincia8));
        localidades.add(new Localidad("Castillo de Locubín", provincia8));
        localidades.add(new Localidad("Cazalilla", provincia8));
        localidades.add(new Localidad("Cazorla", provincia8));
        localidades.add(new Localidad("Chiclana de Segura", provincia8));
        localidades.add(new Localidad("Chilluévar", provincia8));
        localidades.add(new Localidad("Escañuela", provincia8));
        localidades.add(new Localidad("Espelúy", provincia8));
        localidades.add(new Localidad("Frailes", provincia8));
        localidades.add(new Localidad("Fuensanta de Martos", provincia8));
        localidades.add(new Localidad("Fuerte del Rey", provincia8));
        localidades.add(new Localidad("Génave", provincia8));
        localidades.add(new Localidad("Guardia de Jaén, La", provincia8));
        localidades.add(new Localidad("Guarromán", provincia8));
        localidades.add(new Localidad("Higuera de Calatrava", provincia8));
        localidades.add(new Localidad("Hinojares", provincia8));
        localidades.add(new Localidad("Hornos", provincia8));
        localidades.add(new Localidad("Huelma", provincia8));
        localidades.add(new Localidad("Huesa", provincia8));
        localidades.add(new Localidad("Ibros", provincia8));
        localidades.add(new Localidad("Iruela, La", provincia8));
        localidades.add(new Localidad("Iznatoraf", provincia8));
        localidades.add(new Localidad("Jabalquinto", provincia8));
        localidades.add(new Localidad("Jaén", provincia8));
        localidades.add(new Localidad("Jamilena", provincia8));
        localidades.add(new Localidad("Jimena", provincia8));
        localidades.add(new Localidad("Jódar", provincia8));
        localidades.add(new Localidad("Lahiguera", provincia8));
        localidades.add(new Localidad("Larva", provincia8));
        localidades.add(new Localidad("Linares", provincia8));
        localidades.add(new Localidad("Lopera", provincia8));
        localidades.add(new Localidad("Lupión", provincia8));
        localidades.add(new Localidad("Mancha Real", provincia8));
        localidades.add(new Localidad("Marmolejo", provincia8));
        localidades.add(new Localidad("Martos", provincia8));
        localidades.add(new Localidad("Mengíbar", provincia8));
        localidades.add(new Localidad("Montizón", provincia8));
        localidades.add(new Localidad("Navas de San Juan", provincia8));
        localidades.add(new Localidad("Noalejo", provincia8));
        localidades.add(new Localidad("Orcera", provincia8));
        localidades.add(new Localidad("Peal de Becerro", provincia8));
        localidades.add(new Localidad("Pegalajar", provincia8));
        localidades.add(new Localidad("Porcuna", provincia8));
        localidades.add(new Localidad("Pozo Alcón", provincia8));
        localidades.add(new Localidad("Puente de Génave", provincia8));
        localidades.add(new Localidad("Puerta de Segura, La", provincia8));
        localidades.add(new Localidad("Quesada", provincia8));
        localidades.add(new Localidad("Rus", provincia8));
        localidades.add(new Localidad("Sabiote", provincia8));
        localidades.add(new Localidad("Santa Elena", provincia8));
        localidades.add(new Localidad("Santiago de Calatrava", provincia8));
        localidades.add(new Localidad("Santiago-Pontones", provincia8));
        localidades.add(new Localidad("Santisteban del Puerto", provincia8));
        localidades.add(new Localidad("Santo Tomé", provincia8));
        localidades.add(new Localidad("Segura de la Sierra", provincia8));
        localidades.add(new Localidad("Siles", provincia8));
        localidades.add(new Localidad("Sorihuela del Guadalimar", provincia8));
        localidades.add(new Localidad("Torreblascopedro", provincia8));
        localidades.add(new Localidad("Torredelcampo", provincia8));
        localidades.add(new Localidad("Torredonjimeno", provincia8));
        localidades.add(new Localidad("Torreperogil", provincia8));
        localidades.add(new Localidad("Torres", provincia8));
        localidades.add(new Localidad("Torres de Albánchez", provincia8));
        localidades.add(new Localidad("Úbeda", provincia8));
        localidades.add(new Localidad("Valdepeñas de Jaén", provincia8));
        localidades.add(new Localidad("Vilches", provincia8));
        localidades.add(new Localidad("Villacarrillo", provincia8));
        localidades.add(new Localidad("Villanueva de la Reina", provincia8));
        localidades.add(new Localidad("Villanueva del Arzobispo", provincia8));
        localidades.add(new Localidad("Villardompardo", provincia8));
        localidades.add(new Localidad("Villares, Los", provincia8));
        localidades.add(new Localidad("Villarrodrigo", provincia8));
        localidades.add(new Localidad("Villatorres", provincia8));
        provincia8.setLocalidades(localidades);
        provincias.add(provincia8);

        //Huelva
        localidades = new ArrayList<>();
        localidades.add(new Localidad("Adamuz", provincia9));
        localidades.add(new Localidad("Aguilar de la Frontera", provincia9));
        localidades.add(new Localidad("Alcaracejos", provincia9));
        localidades.add(new Localidad("Almedinilla", provincia9));
        localidades.add(new Localidad("Almodóvar del Río", provincia9));
        localidades.add(new Localidad("Añora", provincia9));
        localidades.add(new Localidad("Baena", provincia9));
        localidades.add(new Localidad("Belalcázar", provincia9));
        localidades.add(new Localidad("Belmez", provincia9));
        localidades.add(new Localidad("Benamejí", provincia9));
        localidades.add(new Localidad("Blázquez, Los", provincia9));
        localidades.add(new Localidad("Bujalance", provincia9));
        localidades.add(new Localidad("Cabra", provincia9));
        localidades.add(new Localidad("Cañete de las Torres", provincia9));
        localidades.add(new Localidad("Carcabuey", provincia9));
        localidades.add(new Localidad("Cardeña", provincia9));
        localidades.add(new Localidad("Carlota, La", provincia9));
        localidades.add(new Localidad("Carpio, El", provincia9));
        localidades.add(new Localidad("Castro del Río", provincia9));
        localidades.add(new Localidad("Conquista", provincia9));
        localidades.add(new Localidad("Córdoba", provincia9));
        localidades.add(new Localidad("Doña Mencía", provincia9));
        localidades.add(new Localidad("Dos Torres", provincia9));
        localidades.add(new Localidad("Encinas Reales", provincia9));
        localidades.add(new Localidad("Espejo", provincia9));
        localidades.add(new Localidad("Espiel", provincia9));
        localidades.add(new Localidad("Fernán-Núñez", provincia9));
        localidades.add(new Localidad("Fuente la Lancha", provincia9));
        localidades.add(new Localidad("Fuente Obejuna", provincia9));
        localidades.add(new Localidad("Fuente Palmera", provincia9));
        localidades.add(new Localidad("Fuente-Tójar", provincia9));
        localidades.add(new Localidad("Granjuela, La", provincia9));
        localidades.add(new Localidad("Guadalcázar", provincia9));
        localidades.add(new Localidad("Guijo, El", provincia9));
        localidades.add(new Localidad("Hinojosa del Duque", provincia9));
        localidades.add(new Localidad("Hornachuelos", provincia9));
        localidades.add(new Localidad("Iznájar", provincia9));
        localidades.add(new Localidad("Lucena", provincia9));
        localidades.add(new Localidad("Luque", provincia9));
        localidades.add(new Localidad("Montalbán de Córdoba", provincia9));
        localidades.add(new Localidad("Montemayor", provincia9));
        localidades.add(new Localidad("Montilla", provincia9));
        localidades.add(new Localidad("Montoro", provincia9));
        localidades.add(new Localidad("Monturque", provincia9));
        localidades.add(new Localidad("Moriles", provincia9));
        localidades.add(new Localidad("Nueva Carteya", provincia9));
        localidades.add(new Localidad("Obejo", provincia9));
        localidades.add(new Localidad("Palenciana", provincia9));
        localidades.add(new Localidad("Palma del Río", provincia9));
        localidades.add(new Localidad("Pedro Abad", provincia9));
        localidades.add(new Localidad("Pedroche", provincia9));
        localidades.add(new Localidad("Peñarroya-Pueblonuevo", provincia9));
        localidades.add(new Localidad("Posadas", provincia9));
        localidades.add(new Localidad("Pozoblanco", provincia9));
        localidades.add(new Localidad("Priego de Córdoba", provincia9));
        localidades.add(new Localidad("Puente Genil", provincia9));
        localidades.add(new Localidad("Rambla, La", provincia9));
        localidades.add(new Localidad("Rute", provincia9));
        localidades.add(new Localidad("San Sebastián de los Ballesteros", provincia9));
        localidades.add(new Localidad("Santaella", provincia9));
        localidades.add(new Localidad("Santa Eufemia", provincia9));
        localidades.add(new Localidad("Torrecampo", provincia9));
        localidades.add(new Localidad("Valenzuela", provincia9));
        localidades.add(new Localidad("Valsequillo", provincia9));
        localidades.add(new Localidad("Victoria, La", provincia9));
        localidades.add(new Localidad("Villa del Río", provincia9));
        localidades.add(new Localidad("Villafranca de Córdoba", provincia9));
        localidades.add(new Localidad("Villaharta", provincia9));
        localidades.add(new Localidad("Villanueva de Córdoba", provincia9));
        localidades.add(new Localidad("Villanueva del Duque", provincia9));
        localidades.add(new Localidad("Villanueva del Rey", provincia9));
        localidades.add(new Localidad("Villaralto", provincia9));
        localidades.add(new Localidad("Villaviciosa de Córdoba", provincia9));
        localidades.add(new Localidad("Viso, El", provincia9));
        localidades.add(new Localidad("Zuheros", provincia9));
        provincia9.setLocalidades(localidades);
        provincias.add(provincia9);

        //Malaga
        localidades = new ArrayList<>();
        //        localidades.add(new Localidad("Alhaurín de la Torre", provincia3));
//        localidades.add(new Localidad("Alameda", provincia3));
//        localidades.add(new Localidad("Alora", provincia3));
//        localidades.add(new Localidad("Antequera", provincia3));
//        localidades.add(new Localidad("Ardales", provincia3));
//        localidades.add(new Localidad("Arena", provincia3));
//        localidades.add(new Localidad("Arriate", provincia3));
//        localidades.add(new Localidad("Atajate", provincia3));
//        localidades.add(new Localidad("Benadalid", provincia3));
//        localidades.add(new Localidad("Benahavis", provincia3));
//        localidades.add(new Localidad("Benalauria", provincia3));
//        localidades.add(new Localidad("Benalmadena", provincia3));
//        localidades.add(new Localidad("Benamargosa", provincia3));
//        localidades.add(new Localidad("Benamocarra", provincia3));
//        localidades.add(new Localidad("Benamorraca", provincia3));
//        localidades.add(new Localidad("Benaojan", provincia3));
//        localidades.add(new Localidad("Benarraba", provincia3));
//        localidades.add(new Localidad("Campillos", provincia3));
//        localidades.add(new Localidad("Canete la Real", provincia3));
//        localidades.add(new Localidad("Canillas de Aceituno", provincia3));
//        localidades.add(new Localidad("Canillas de Albaida", provincia3));
//        localidades.add(new Localidad("Carratraca", provincia3));
//        localidades.add(new Localidad("Cartajima", provincia3));
//        localidades.add(new Localidad("Casabermeja", provincia3));
//        localidades.add(new Localidad("Casarabonela", provincia3));
//        localidades.add(new Localidad("Coin", provincia3));
//        localidades.add(new Localidad("Colmenar", provincia3));
//        localidades.add(new Localidad("Comares", provincia3));
//        localidades.add(new Localidad("Competa", provincia3));
//        localidades.add(new Localidad("Cortes de la Frontera", provincia3));
//        localidades.add(new Localidad("Cuevas Bajas", provincia3));
//        localidades.add(new Localidad("Cuevas de San Marcos", provincia3));
//        localidades.add(new Localidad("Cuevas del Becerro", provincia3));
//        localidades.add(new Localidad("Cutar", provincia3));
//        localidades.add(new Localidad("El Borge", provincia3));
//        localidades.add(new Localidad("El Burgo", provincia3));
//        localidades.add(new Localidad("Estepona", provincia3));
//        localidades.add(new Localidad("Farajan", provincia3));
//        localidades.add(new Localidad("Frigiliana", provincia3));
//        localidades.add(new Localidad("Fuengirola", provincia3));
//        localidades.add(new Localidad("Fuente de Piedra", provincia3));
//        localidades.add(new Localidad("Gaucin", provincia3));
//        localidades.add(new Localidad("Guaro", provincia3));
//        localidades.add(new Localidad("Humilladero", provincia3));
//        localidades.add(new Localidad("Igualeja", provincia3));
//        localidades.add(new Localidad("Iznate", provincia3));
//        localidades.add(new Localidad("Jimena de Libar", provincia3));
//        localidades.add(new Localidad("Jubrique", provincia3));
//        localidades.add(new Localidad("Juzcar", provincia3));
//        localidades.add(new Localidad("Macharaviya", provincia3));
//        localidades.add(new Localidad("Málaga", provincia3));
//        localidades.add(new Localidad("Marbella", provincia3));
//        localidades.add(new Localidad("Mijas", provincia3));
//        localidades.add(new Localidad("Moclinejo", provincia3));
//        localidades.add(new Localidad("Mollina", provincia3));
//        localidades.add(new Localidad("Monda", provincia3));
//        localidades.add(new Localidad("Montejaque", provincia3));
//        localidades.add(new Localidad("Nerja", provincia3));
//        localidades.add(new Localidad("Ojen", provincia3));
//        localidades.add(new Localidad("Parauta", provincia3));
//        localidades.add(new Localidad("Periana", provincia3));
//        localidades.add(new Localidad("Pizarra", provincia3));
//        localidades.add(new Localidad("Pujerra", provincia3));
//        localidades.add(new Localidad("Rincon de la Victoria", provincia3));
//        localidades.add(new Localidad("Riogordo", provincia3));
//        localidades.add(new Localidad("Ronda", provincia3));
//        localidades.add(new Localidad("Salares", provincia3));
//        localidades.add(new Localidad("Sayalonga", provincia3));
//        localidades.add(new Localidad("Sedella", provincia3));
//        localidades.add(new Localidad("Sierra de Yeguas", provincia3));
//        localidades.add(new Localidad("Teba", provincia3));
//        localidades.add(new Localidad("Tolox", provincia3));
//        localidades.add(new Localidad("Torremolinos", provincia3));
//        localidades.add(new Localidad("Torrox", provincia3));
//        localidades.add(new Localidad("Totalan", provincia3));
//        localidades.add(new Localidad("Valle de Abdalajis", provincia3));
//        localidades.add(new Localidad("Villanueva de Tapia", provincia3));
//        localidades.add(new Localidad("Villanueva del Rosario", provincia3));
//        localidades.add(new Localidad("Villanueva del Trabuco", provincia3));
//        localidades.add(new Localidad("Vinuela", provincia3));
//        localidades.add(new Localidad("Yunquera", provincia3));
        localidades.add(new Localidad("Málaga", provincia3));
        localidades.add(new Localidad("Alhaurín de la Torre", provincia3));
        localidades.add(new Localidad("Benalmadena", provincia3));
        localidades.add(new Localidad("Nerja", provincia3));
        localidades.add(new Localidad("Rincon de la Victoria", provincia3));
        localidades.add(new Localidad("Torremolinos", provincia3));
        provincia3.setLocalidades(localidades);
        provincias.add(provincia3);
        //Collections.sort(localidades ,Collections.reverseOrder());
    }

    public List<Provincia> getProvincias() {
        return provincias;
    }

    public List<Localidad> getLocalidades() {
        Collections.sort(localidades, new Comparator<Localidad>() {
            @Override
            public int compare(Localidad o1, Localidad o2) {
                return o1.getNombre().compareTo(o2.getNombre());
            }
        });
        return localidades;
    }

    public void onCambioProvincia() {
//        System.out.println("Provincia: " + provincia);
//        System.out.println("Localidad: " + localidad);
//        System.out.println();
        localidad = provincia;
        if (provincia != null && !provincia.equals("")) {
            //localidades = provincias.get(provincias.indexOf(provincia)).getLocalidades();
            localidades = provinciaGetLocalidades(provincia);
        } else {
            localidades = new ArrayList<>();
        }
    }

    private List<Localidad> provinciaGetLocalidades(String provincia) {
//        System.out.println("Provincia: " + provincia);
//        System.out.println();
        List<Localidad> loc = new ArrayList<>();
        for (Provincia p : provincias) {
            if (p.getNombre().equals(provincia)) {
                loc = p.getLocalidades();
            }
        }
        Collections.sort(localidades, new Comparator<Localidad>() {
            @Override
            public int compare(Localidad o1, Localidad o2) {
                return o1.getNombre().compareTo(o2.getNombre());
            }
        });
        return loc;
    }

    public String getProvincia() {
        Collections.sort(provincias, new Comparator<Provincia>() {
            @Override
            public int compare(Provincia o1, Provincia o2) {
                return o1.getNombre().compareTo(o2.getNombre());
            }
        });
        return provincia;
    }

    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    public String getLocalidad() {
        return localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
}
