SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE agenda.Usuario_Tarea DROP FOREIGN KEY FKh4g3703hkoiqwpcr7f7ln26pl;
ALTER TABLE agenda.Usuario_Tarea DROP FOREIGN KEY FK7k6sygmrvjg0l5smp57afeq1u;
ALTER TABLE agenda.Notificacion DROP FOREIGN KEY FKf584afdtx8glf5nnjsytid5kl;
ALTER TABLE agenda.Notificacion DROP FOREIGN KEY FKpkjtdox8eey9m5e7yecp80kxo;
ALTER TABLE agenda.jn_sigue_id DROP FOREIGN KEY FKb2vamopaeeuc2ifmrwhw7slhp;
ALTER TABLE agenda.jn_sigue_id DROP FOREIGN KEY FKs8kjpmi65fsicwu74lvpe5n83;
ALTER TABLE agenda.jn_megusta_id DROP FOREIGN KEY FKa52g9ffuufl77w57q9e5u3sf1;
ALTER TABLE agenda.jn_megusta_id DROP FOREIGN KEY FKsv6e8tl6af3r3wfyj7ig6tf1u;
ALTER TABLE agenda.jn_asiste_id DROP FOREIGN KEY FKibsvj08cy6cmv51d1wdcx5jwl;
ALTER TABLE agenda.jn_asiste_id DROP FOREIGN KEY FKovbsrolbousftowmxb09rx6m5;
ALTER TABLE agenda.Evento_Etiqueta DROP FOREIGN KEY FKfsjgd7du8vbhhau6hfbdf3n86;
ALTER TABLE agenda.Evento_Etiqueta DROP FOREIGN KEY FKdkkym5px3t0ck8qtxka1n4mdi;
ALTER TABLE agenda.Evento_Destinatario DROP FOREIGN KEY FKs1epe46cg008ccq5ihsoo2hb6;
ALTER TABLE agenda.Evento_Destinatario DROP FOREIGN KEY FKcrc1dxci5iw7bv34yiip2aarb;
ALTER TABLE agenda.Comentario DROP FOREIGN KEY FKgmk41wggq7acr5cin4y6petdr;
ALTER TABLE agenda.Comentario DROP FOREIGN KEY FKq2utsndscehnpau990r39jlgg;
ALTER TABLE agenda.Evento DROP FOREIGN KEY FK56opiht2l9kwnn8dax44cru9g;
ALTER TABLE agenda.Evento DROP FOREIGN KEY FK98uda8shy2qbom5y75jeh0d2h;
ALTER TABLE agenda.Tarea DROP FOREIGN KEY FKohs1nkl0d2n8co2qga7urk4bu;
ALTER TABLE agenda.Localidad DROP FOREIGN KEY FKf8uibl8ose2ibp6pps8jsqpqi;
DROP TABLE agenda.Usuario_Tarea;
DROP TABLE agenda.Notificacion;
DROP TABLE agenda.jn_sigue_id;
DROP TABLE agenda.jn_megusta_id;
DROP TABLE agenda.jn_asiste_id;
DROP TABLE agenda.Evento_Etiqueta;
DROP TABLE agenda.Evento_Destinatario;
DROP TABLE agenda.Comentario;
DROP TABLE agenda.Evento;
DROP TABLE agenda.Tarea;
DROP TABLE agenda.Localidad;
DROP TABLE agenda.Usuario;
DROP TABLE agenda.Provincia;
DROP TABLE agenda.Etiqueta;
DROP TABLE agenda.Destinatario;
