ALTER TABLE agenda.jn_notificaciones_id DROP FOREIGN KEY FKbp6k5qsbo9knc133imhpk3as2;
ALTER TABLE agenda.jn_notificaciones_id DROP FOREIGN KEY FK486syap1s5jap40gfow7pwvw9;
ALTER TABLE agenda.jn_megusta_id DROP FOREIGN KEY FKa52g9ffuufl77w57q9e5u3sf1;
ALTER TABLE agenda.jn_megusta_id DROP FOREIGN KEY FKsv6e8tl6af3r3wfyj7ig6tf1u;
ALTER TABLE agenda.jn_etiqueta_id DROP FOREIGN KEY FK9aijur6g9lccsi7fb6hega1hr;
ALTER TABLE agenda.jn_etiqueta_id DROP FOREIGN KEY FKkynorwdijmpyv1utmu0py9ax4;
ALTER TABLE agenda.jn_destinatario_id DROP FOREIGN KEY FK4d7f76lcbl4ns95qfy8dsohmf;
ALTER TABLE agenda.jn_destinatario_id DROP FOREIGN KEY FK9amxm8d403yft4astl2qjb3tu;
ALTER TABLE agenda.jn_comentarios_id DROP FOREIGN KEY FKpwwkvvej5bpsklunm6mvik337;
ALTER TABLE agenda.jn_comentarios_id DROP FOREIGN KEY FK3k1qhp4v45uoqm8nkaykx1ngr;
ALTER TABLE agenda.jn_asiste_id DROP FOREIGN KEY FKibsvj08cy6cmv51d1wdcx5jwl;
ALTER TABLE agenda.jn_asiste_id DROP FOREIGN KEY FKovbsrolbousftowmxb09rx6m5;
ALTER TABLE agenda.Evento DROP FOREIGN KEY FK56opiht2l9kwnn8dax44cru9g;
ALTER TABLE agenda.Evento DROP FOREIGN KEY FKk49b0cr888estc30rolh0tp2r;
ALTER TABLE agenda.Comentario DROP FOREIGN KEY FKgmk41wggq7acr5cin4y6petdr;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE agenda.jn_notificaciones_id;
DROP TABLE agenda.jn_megusta_id;
DROP TABLE agenda.jn_etiqueta_id;
DROP TABLE agenda.jn_destinatario_id;
DROP TABLE agenda.jn_comentarios_id;
DROP TABLE agenda.jn_asiste_id;
DROP TABLE agenda.Evento;
DROP TABLE agenda.Comentario;
DROP TABLE agenda.Usuario;
DROP TABLE agenda.Notificacion;
DROP TABLE agenda.Localidad;
DROP TABLE agenda.Etiqueta;
DROP TABLE agenda.Destinatario;
DROP TABLE agenda.Usuario_Notificacion;
DROP TABLE agenda.Usuario_Evento;
DROP TABLE agenda.Usuario_Comentario;
DROP TABLE agenda.Tarea_Usuario;
DROP TABLE agenda.Tarea;
DROP TABLE agenda.Provincia;
DROP TABLE agenda.jn_tareas_id;
DROP TABLE agenda.jn_tarea_peticion_id;
DROP TABLE agenda.jn_sigue_id;
